### ISSUE TITLE
Cannot install on OSX 10 using command from INSTALL file

### ISSUE THREAD

**Issue by energo80** [Ayuntamiento-Zaragoza/dxf2gml-catastro#2]
prezes.procesy5.pl:dxf2gml-catastro a.binder$ python setup.py --command packages=stdeb.command bdist_deb
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_deb'
prezes.procesy5.pl:dxf2gml-catastro a.binder$

**Comment by jact** [comment]
Do you have installed all dependencies on OSX 10?

```
* Python >= 2.7
* python-setuptools
* python-stdeb (to create a DEB package)
* python-django >= 1.9
* python-gdal >= 1.10
```

**Comment by agacias** [comment]
This instructions are for an OS with apt PMS.
In OSX you can build a docker container: 
https://github.com/Ayuntamiento-Zaragoza/dxf2gml-catastro/tree/master/docker
